USE SeaBattleTest_FINAL
GO

CREATE TABLE ShipTypes(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
[Type] NVARCHAR(20) NOT NULL
);

CREATE TABLE Ships (
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
TypeId INT NOT NULL REFERENCES ShipTypes (Id) ON DELETE CASCADE ON UPDATE CASCADE,
Velocity INT NOT NULL,
[Range] INT NOT NULL,
Size INT NOT NULL
);

CREATE TABLE Points(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
X INT NOT NULL,
Y INT NOT NULL
);

CREATE TABLE BattleFields(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
SideLength INT NOT NULL
);

CREATE TABLE Cells(
Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
PointID INT  NOT NULL REFERENCES Points (Id) ON DELETE CASCADE ON UPDATE CASCADE, 
ShipID INT NULL REFERENCES Ships (Id)  ON DELETE SET NULL ON UPDATE CASCADE,
BattleFieldID INT NOT NULL REFERENCES BattleFields(Id) ON DELETE CASCADE ON UPDATE CASCADE
);
